=== museumsvictoria/nodel-recipes/Frontend/Mk1/content/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="row">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="column" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="gap"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="row" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="title" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pill">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="badge" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="value" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="badge">
		<xs:complexType>
			<xs:attribute name="event" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="meter">
		<xs:complexType>
			<xs:attribute name="event" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pages">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="page"/>
			</xs:sequence>
			<xs:attribute name="title" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pills">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pill" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="event" use="required" type="xs:string"/>
			<xs:attribute name="action" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="range">
		<xs:complexType>
			<xs:attribute name="action" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="button">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="badge" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="action" use="required" type="xs:string"/>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="btn-default"/>
						<xs:enumeration value="btn-primary"/>
            <xs:enumeration value="btn-warning"/>
            <xs:enumeration value="btn-danger"/>
            <xs:enumeration value="btn-success"/>
            <xs:enumeration value="btn-info"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="column">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:choice>
					<xs:element ref="buttongroup"/>
					<xs:element ref="status" maxOccurs="unbounded"/>
					<xs:element ref="select" maxOccurs="unbounded"/>
					<xs:element ref="button" maxOccurs="unbounded"/>
					<xs:element ref="range" maxOccurs="unbounded"/>
					<xs:element ref="pills" maxOccurs="unbounded"/>
					<xs:element ref="meter" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="sm" use="required" type="xs:byte"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="select">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="btn-default"/>
						<xs:enumeration value="btn-primary"/>
            <xs:enumeration value="btn-warning"/>
            <xs:enumeration value="btn-danger"/>
            <xs:enumeration value="btn-success"/>
            <xs:enumeration value="btn-info"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="event" use="required" type="xs:string"/>
			<xs:attribute name="action" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="status">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="badge" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="event" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="buttongroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="button" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== museumsvictoria/nodel-recipes/Yamaha XMV Series amplifier (ready for MTX3, MTX5-D, MRX7-D, EXi8, EXo8)/content/frontend.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl" ?>
<pages title='Yamaha Amplifier (XMV) Series' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
  <page title='Main'>
    <row>
      <column sm="3">
        <status event="Status">Status</status>
        
        <title>Manual</title>
        <link url="http://download.yamaha.com/api/asset/file/?language=en&amp;site=countrysite-master.prod.wsys.yamaha.com&amp;asset_id=63959"/>
        
        <title>Device</title>
        Firmware
        <panel event="FirmwareVersion"></panel>
        
        Run Mode
        <panel event="DeviceRunMode"></panel>
        
        Error Status
        <panel event="DeviceErrorStatus"></panel>
        
        <title>Utility</title>
        <select event="Input Select" action="Input Select">
          <item value="Analog">Analog</item>
          <item value="Digital">Digital</item>
          <item value="Multiple">Multiple</item>
        </select>
        
        <title>Sensitivity</title>
        <select event="InputSensitivity" action="InputSensitivity">
          <item value="-20dBFS">-20dBFS</item>
          <item value="-3dBFS">-3dBFS</item>
        </select>
      </column>
      <column sm="3">
        <title>Power</title>
        <partialswitch event="Power" action="Power"></partialswitch>
        
        <title>Attenuation</title>
        <range action='Channel1Att' event="Channel1Att" min="-90" max="0"/>
        <range action='Channel2Att' event="Channel2Att" min="-90" max="0"/>
        <range action='Channel3Att' event="Channel3Att" min="-90" max="0"/>
        <range action='Channel4Att' event="Channel4Att" min="-90" max="0"/>
        <range action='Channel5Att' event="Channel5Att" min="-90" max="0"/>
        <range action='Channel6Att' event="Channel6Att" min="-90" max="0"/>
        <range action='Channel7Att' event="Channel7Att" min="-90" max="0"/>
        <range action='Channel8Att' event="Channel8Att" min="-90" max="0"/>
      </column>
      <column sm="2">
        <title>Muting</title>
        <partialswitch event="Channel1Mute" action="Channel1Mute"></partialswitch>
        <partialswitch event="Channel2Mute" action="Channel2Mute"></partialswitch>
        <partialswitch event="Channel3Mute" action="Channel3Mute"></partialswitch>
        <partialswitch event="Channel4Mute" action="Channel4Mute"></partialswitch>
        <partialswitch event="Channel5Mute" action="Channel5Mute"></partialswitch>
        <partialswitch event="Channel6Mute" action="Channel6Mute"></partialswitch>
        <partialswitch event="Channel7Mute" action="Channel7Mute"></partialswitch>
        <partialswitch event="Channel8Mute" action="Channel8Mute"></partialswitch>
      </column>
      <column sm="4">
        <title>Outputs</title>
        <meter event="Output1Meter"/>
        <meter event="Output2Meter"/>
        <meter event="Output3Meter"/>
        <meter event="Output4Meter"/>
        <meter event="Output5Meter"/>
        <meter event="Output6Meter"/>
        <meter event="Output7Meter"/>
        <meter event="Output8Meter"/>
        
        <title>Inputs</title>
        <meter event="Input1Meter"/>
        <meter event="Input2Meter"/>
        <meter event="Input3Meter"/>
        <meter event="Input4Meter"/>
        <meter event="Input5Meter"/>
        <meter event="Input6Meter"/>
        <meter event="Input7Meter"/>
        <meter event="Input8Meter"/>
        
        <title>Inputs (9 - 16)</title>
        <meter event="Input9Meter" min="-50" max="0"/>
        <meter event="Input10Meter"/>
        <meter event="Input11Meter"/>
        <meter event="Input12Meter"/>
        <meter event="Input13Meter"/>
        <meter event="Input14Meter"/>
        <meter event="Input15Meter"/>
        <meter event="Input16Meter"/>

      </column>
    </row>
  </page>
</pages>

=== museumsvictoria/nodel-recipes/Frontend/content/index-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<pages title='Status Page' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
  <page title='My Control'>
    <row>
      <column sm="3">
        <title>Source</title>
        <pills event="Preset" action="Preset">
          <pill value="PresetChromecast">Chromecast</pill>
          <pill value="PresetTV">TV</pill>
          <pill value="PresetButler">Signage</pill>
          <pill value="PresetSpare1"><badge event="Status2"/>HDMI 1</pill>
          <pill value="PresetSpare2"><badge event="Status2"/>HDMI 2</pill>
        </pills>
      </column>
      <column sm="3">
        <row>
          <column sm="12">
            <title>Source select</title>
            <select class="btn-default" event="Preset" action="Preset">
              <item value="PresetChromecast">Chromecast</item>
              <item value="PresetTV">TV</item>
              <item value="PresetButler">Signage</item>
              <item value="PresetSpare1">HDMI 1</item>
              <item value="PresetSpare2">HDMI 2</item>
            </select>
          </column>
        </row>
        <row>
          <column sm="12">
            <dynamicselect class="btn-default" data="DynamicList" event="Dynamic" action="Dynamic"/>
          </column>
        </row>
        <row>
          <column sm="12">
            <switch class="btn-default" event="Switch" action="Switch"/>
          </column>
        </row>
        <row>
          <column sm="12">
            <partialswitch class="btn-default" event="PartialSwitch" action="PartialSwitch"/>
          </column>
        </row>
      </column>
      <column sm="4">
        <title>Testing status</title>
        <status event="Status1"><badge event="Status2"/><link url="http://nodel.io"/><partialbadge event="PartialSwitch"/>Example status box with badge and partialbadge</status>
        <status event="Status2" page="Testing"><link url="http://nodel.io">Nodel</link><partialswitch class="btn-default" event="PartialSwitch" action="PartialSwitch"/>Example status box with a long title</status>
      </column>
      <column sm="2">
        <title>Meters</title>
        <meter event="Meter1"></meter>
        <meter event="Meter2"></meter>
        <meter event="Meter3" range="db"></meter>
      </column>
    </row>
    <row>
      <column sm="8">
        <row>
          <column sm="12">
            <title>Testing button groups</title>
            <buttongroup>
              <button action='PresetChromecast' class='btn-default'>Chromecast</button>
              <button action='PresetTV' class='btn-default'>TV</button>
              <button action='PresetButler' class='btn-default'>Signage</button>
              <button action='PresetSpare1' class='btn-default'>HDMI 1<badge event="Status2"/></button>
              <button action='PresetSpare2' class='btn-default'>HDMI 2<badge event="Status2"/></button>
            </buttongroup>
          </column>
        </row>
        <row>
          <column sm="12">
            <title>Range</title>
            <range action='Range' event="Range"></range>
          </column>
        </row>
        <row>
          <column sm="6">
            <title>Volume</title>
            <button action='VolumeDown' class='btn-success'>Down</button>
            <button action='VolumeUp' class='btn-success'>Up</button>
          </column>
          <column sm="6">
            <title>Volume momentary</title>
            <button type="momentary" action-off='VolumeStop' action-on='VolumeDownOn' class='btn-success'>Down</button>
            <button type="momentary" action-off='VolumeStop' action-on='VolumeUpOn' class='btn-success'>Up</button>
          </column>
        </row>
      </column>
      <column sm="4">
        <row>
          <column sm="12">
            <title>Testing panel</title>
            <panel height="100" event="Panel"></panel>
          </column>
        </row>
        <row>
          <column sm="12">
            <title>Testing field</title>
            <field event="Field"></field>
          </column>
        </row>
      </column>
    </row>
  </page>
</pages>
